version: "3"
services:
  frontend:
    container_name: frontend
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3002
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
